// Master Event Library — 74 events, all platforms, all website types

export type FunnelStage = "awareness" | "engagement" | "consideration" | "intent" | "conversion" | "retention" | "diagnostic";
export type ConversionRole = "primary" | "secondary" | "remarketing" | "diagnostic";
export type EventPriority = "high" | "medium" | "low";
export type WebsiteType =
  | "lead"
  | "ecommerce"
  | "booking"
  | "local"
  | "content"
  | "saas"
  | "highticket"
  | "restaurant"
  | "realestate"
  | "education"
  | "healthcare"
  | "b2b"
  | "affiliate"
  | "all";

export interface EventDefinition {
  eventKey: string;
  displayName: string;
  description: string;
  websiteTypes: WebsiteType[];
  funnelStage: FunnelStage;
  priority: EventPriority;
  conversionRole: ConversionRole;
  ga4EventName: string;
  googleAdsCategory: string;
  metaEventName: string;
  tiktokEventName: string;
  isStandardEvent: boolean;
  requiredParameters: string[];
  optionalParameters: string[];
  triggerType: "click" | "page_view" | "form_submit" | "custom_event" | "timer";
  triggerLogic: string;
  dataLayerExample: Record<string, unknown>;
  duplicateRisk: "high" | "medium" | "low";
  qaChecklist: string[];
  implementationNotes: string;
  detectionKeywords?: string[];
}

export const EVENT_LIBRARY: EventDefinition[] = [
  // ── Core Events ──────────────────────────────────────────────
  {
    eventKey: "page_view",
    displayName: "Page View",
    description: "User views any page — base tracking for all websites",
    websiteTypes: ["all"],
    funnelStage: "awareness",
    priority: "high",
    conversionRole: "remarketing",
    ga4EventName: "page_view",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "PageView",
    tiktokEventName: "Pageview",
    isStandardEvent: true,
    requiredParameters: ["page_title", "page_location"],
    optionalParameters: ["page_referrer", "content_group"],
    triggerType: "page_view",
    triggerLogic: "All pages — fires on every page load",
    dataLayerExample: { event: "page_view", page_title: "{{Page Title}}", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Open any page → check GA4 DebugView shows page_view", "Check no duplicate page_view fires"],
    implementationNotes: "GTM built-in — use GA4 Configuration tag with All Pages trigger",
  },
  {
    eventKey: "view_content",
    displayName: "View Content",
    description: "User views an important service/product/blog page",
    websiteTypes: ["lead", "content", "affiliate", "highticket", "b2b"],
    funnelStage: "consideration",
    priority: "medium",
    conversionRole: "remarketing",
    ga4EventName: "view_content",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["content_type", "content_id"],
    optionalParameters: ["content_name", "value", "currency"],
    triggerType: "page_view",
    triggerLogic: "URL matches /service/, /product/, /blog/, or specific content pages",
    dataLayerExample: { event: "view_content", content_type: "service", content_id: "page-slug", content_name: "Page Title", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Visit a service/product page → verify view_content fires with correct content_id"],
    implementationNotes: "Use URL-based trigger — add page path pattern for each content category",
  },
  {
    eventKey: "scroll",
    displayName: "Scroll Depth",
    description: "User scrolls to 50% or 90% of page — measures engagement",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "scroll",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["scroll_depth"],
    optionalParameters: ["page_location", "page_title"],
    triggerType: "timer",
    triggerLogic: "Scroll depth 50% or 90% on target pages",
    dataLayerExample: { event: "scroll", scroll_depth: "50", page_title: "{{Page Title}}", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Scroll to 50% — check GA4 scroll event fires", "Check scroll_depth parameter value"],
    implementationNotes: "Use GTM Scroll Depth trigger — set thresholds 50% and 90%",
  },
  {
    eventKey: "cta_click",
    displayName: "CTA Click",
    description: "User clicks any primary call-to-action button",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "cta_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["button_text", "click_url"],
    optionalParameters: ["button_location", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on elements matching CTA button selectors or text patterns",
    dataLayerExample: { event: "cta_click", button_text: "{{Click Text}}", click_url: "{{Click URL}}", button_location: "hero", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click main CTA → verify event fires with correct button_text"],
    implementationNotes: "Use GTM Click trigger with CSS selector filter for CTA buttons",
  },
  {
    eventKey: "outbound_click",
    displayName: "Outbound Link Click",
    description: "User clicks link going to external domain",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "secondary",
    ga4EventName: "outbound_click",
    googleAdsCategory: "OUTBOUND_CLICK",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["click_url", "link_domain"],
    optionalParameters: ["link_text", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on <a> href starting with http where domain differs from current site",
    dataLayerExample: { event: "outbound_click", click_url: "{{Click URL}}", link_domain: "{{Click URL Hostname}}", link_text: "{{Click Text}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click external link → check outbound_click fires", "Verify internal links do NOT fire this event"],
    implementationNotes: "GTM Just Links trigger with condition: Click URL does not contain {{Page Hostname}}",
  },
  {
    eventKey: "file_download",
    displayName: "File Download",
    description: "User clicks to download a file (PDF, brochure, etc.)",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "file_download",
    googleAdsCategory: "DOWNLOAD",
    metaEventName: "ViewContent",
    tiktokEventName: "Download",
    isStandardEvent: false,
    requiredParameters: ["file_name", "file_extension", "link_url"],
    optionalParameters: ["file_size", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on href ending with .pdf, .doc, .xlsx, .zip, or download attribute",
    dataLayerExample: { event: "file_download", file_name: "brochure.pdf", file_extension: "pdf", link_url: "{{Click URL}}", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click a PDF link → verify file_download fires with correct file_name"],
    implementationNotes: "GTM Click trigger with regex match on file extensions: \\.pdf|\\.doc|\\.xlsx|\\.zip",
  },
  {
    eventKey: "view_search_results",
    displayName: "View Search Results",
    description: "User performs a site search and sees results",
    websiteTypes: ["ecommerce", "content", "saas"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "view_search_results",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "Search",
    tiktokEventName: "Search",
    isStandardEvent: true,
    requiredParameters: ["search_term"],
    optionalParameters: ["search_results_count"],
    triggerType: "page_view",
    triggerLogic: "URL contains ?s= or ?q= or /search/",
    dataLayerExample: { event: "view_search_results", search_term: "{{Query Parameter: q}}", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Search on site → check view_search_results fires with search_term"],
    implementationNotes: "URL-based trigger matching search query parameters",
  },
  {
    eventKey: "site_search",
    displayName: "Site Search",
    description: "User types in search box — fire before results",
    websiteTypes: ["ecommerce", "content"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "site_search",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "Search",
    tiktokEventName: "Search",
    isStandardEvent: false,
    requiredParameters: ["search_term"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "Form submit on search box",
    dataLayerExample: { event: "site_search", search_term: "user query" },
    duplicateRisk: "low",
    qaChecklist: ["Type in search → verify site_search fires"],
    implementationNotes: "GTM Form submit trigger on search form, or dataLayer push from developer",
  },
  {
    eventKey: "video_start",
    displayName: "Video Start",
    description: "User starts playing an embedded video",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "video_start",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["video_title", "video_url"],
    optionalParameters: ["video_provider", "video_duration"],
    triggerType: "custom_event",
    triggerLogic: "YouTube API onStateChange = 1 (playing) at 0% progress",
    dataLayerExample: { event: "video_start", video_title: "Product Demo", video_url: "{{video_url}}", video_provider: "youtube", video_percent: 0 },
    duplicateRisk: "medium",
    qaChecklist: ["Play video → check video_start fires once", "Check video_title populated correctly"],
    implementationNotes: "Enable YouTube Video trigger in GTM — built-in video trigger handles this",
  },
  {
    eventKey: "video_progress",
    displayName: "Video Progress",
    description: "User watches video to 25%, 50%, 75% milestone",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "video_progress",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["video_title", "video_url", "video_percent"],
    optionalParameters: ["video_current_time"],
    triggerType: "custom_event",
    triggerLogic: "YouTube API at 25, 50, 75% thresholds",
    dataLayerExample: { event: "video_progress", video_title: "Demo", video_url: "{{video_url}}", video_percent: 50 },
    duplicateRisk: "low",
    qaChecklist: ["Watch to 50% → check video_progress fires with video_percent=50"],
    implementationNotes: "GTM YouTube Video trigger with thresholds 25, 50, 75",
  },
  {
    eventKey: "video_complete",
    displayName: "Video Complete",
    description: "User watches video to 90%+ (near complete)",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "video_complete",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["video_title", "video_url", "video_percent"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "YouTube API at 90% or end of video",
    dataLayerExample: { event: "video_complete", video_title: "Demo", video_url: "{{video_url}}", video_percent: 90 },
    duplicateRisk: "low",
    qaChecklist: ["Watch to 90% → check video_complete fires"],
    implementationNotes: "GTM YouTube trigger at 90% threshold",
  },
  // ── Contact Events ────────────────────────────────────────────
  {
    eventKey: "contact_click",
    displayName: "Contact Click",
    description: "Generic contact intent click — any contact channel",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "secondary",
    ga4EventName: "contact_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["contact_method", "click_url"],
    optionalParameters: ["button_text", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on any contact-intent button (fallback when specific method unknown)",
    dataLayerExample: { event: "contact_click", contact_method: "unknown", click_url: "{{Click URL}}", button_text: "{{Click Text}}" },
    duplicateRisk: "medium",
    qaChecklist: ["Click contact button → verify contact_click fires"],
    implementationNotes: "Use as fallback; prefer specific events (line_click, tel_click, etc.)",
    detectionKeywords: ["ติดต่อ", "ติดต่อเรา", "Contact", "Contact Us", "Inquiry", "สอบถาม"],
  },
  {
    eventKey: "line_click",
    displayName: "LINE Click",
    description: "User clicks LINE button — high intent lead action",
    websiteTypes: ["lead", "local", "booking", "highticket", "restaurant", "healthcare", "realestate", "education"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "line_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["click_url", "button_text"],
    optionalParameters: ["line_id", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on href containing line.me, lin.ee, page.line.me, or @ LINE OA",
    dataLayerExample: { event: "line_click", event_id: "line_{{timestamp}}", click_url: "{{Click URL}}", button_text: "{{Click Text}}", lead_type: "line", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click LINE button → check line_click fires", "Verify click_url contains line.me or lin.ee", "Check event appears in Google Ads conversion", "Check Meta Contact event fires"],
    implementationNotes: "KEY EVENT — configure as primary conversion in Google Ads + Meta",
    detectionKeywords: ["line.me", "lin.ee", "LINE", "แอดไลน์", "ไลน์", "ทักไลน์", "Add LINE", "เพิ่มเพื่อน"],
  },
  {
    eventKey: "tel_click",
    displayName: "Phone Click",
    description: "User clicks phone/tel link — high intent call",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "tel_click",
    googleAdsCategory: "PHONE_CALL_LEADS",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["phone_number", "button_text"],
    optionalParameters: ["page_location", "lead_type"],
    triggerType: "click",
    triggerLogic: "Click on href starting with tel:",
    dataLayerExample: { event: "tel_click", event_id: "tel_{{timestamp}}", phone_number: "{{Click URL}}", button_text: "{{Click Text}}", lead_type: "phone", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click phone link → verify tel_click fires", "Check phone_number populated", "Verify Google Ads PHONE_CALL_LEADS conversion fires"],
    implementationNotes: "KEY EVENT — configure as primary conversion in Google Ads",
    detectionKeywords: ["tel:", "โทร", "โทรเลย", "Call", "Call Now", "เบอร์โทร", "ติดต่อเบอร์"],
  },
  {
    eventKey: "email_click",
    displayName: "Email Click",
    description: "User clicks email/mailto link",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "email_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["email_address", "button_text"],
    optionalParameters: ["page_location"],
    triggerType: "click",
    triggerLogic: "Click on href starting with mailto:",
    dataLayerExample: { event: "email_click", event_id: "email_{{timestamp}}", email_address: "{{Click URL}}", button_text: "{{Click Text}}", lead_type: "email", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click email link → verify email_click fires with email_address"],
    implementationNotes: "Usually secondary — use mailto: trigger in GTM",
    detectionKeywords: ["mailto:", "email", "Email", "อีเมล", "ส่งอีเมล"],
  },
  {
    eventKey: "whatsapp_click",
    displayName: "WhatsApp Click",
    description: "User clicks WhatsApp button",
    websiteTypes: ["lead", "local", "restaurant"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "whatsapp_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["click_url", "button_text"],
    optionalParameters: ["phone_number", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on href containing wa.me or whatsapp",
    dataLayerExample: { event: "whatsapp_click", event_id: "wa_{{timestamp}}", click_url: "{{Click URL}}", button_text: "{{Click Text}}", lead_type: "whatsapp" },
    duplicateRisk: "low",
    qaChecklist: ["Click WhatsApp button → verify event fires"],
    implementationNotes: "wa.me link trigger",
    detectionKeywords: ["wa.me", "whatsapp", "WhatsApp"],
  },
  {
    eventKey: "messenger_click",
    displayName: "Messenger Click",
    description: "User clicks Facebook Messenger button",
    websiteTypes: ["lead", "local"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "primary",
    ga4EventName: "messenger_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["click_url", "button_text"],
    optionalParameters: ["page_location"],
    triggerType: "click",
    triggerLogic: "Click on href containing m.me or messenger",
    dataLayerExample: { event: "messenger_click", event_id: "ms_{{timestamp}}", click_url: "{{Click URL}}", button_text: "{{Click Text}}", lead_type: "messenger" },
    duplicateRisk: "low",
    qaChecklist: ["Click Messenger link → verify event fires"],
    implementationNotes: "m.me link trigger",
    detectionKeywords: ["m.me", "messenger", "Messenger"],
  },
  {
    eventKey: "chat_click",
    displayName: "Chat Widget Open",
    description: "User opens live chat widget",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "chat_click",
    googleAdsCategory: "CONTACT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["chat_provider"],
    optionalParameters: ["page_location"],
    triggerType: "custom_event",
    triggerLogic: "Chat widget API event on open (Tidio/Intercom/Crisp/Zendesk/Tawk callback)",
    dataLayerExample: { event: "chat_click", chat_provider: "Tidio", page_location: "{{Page URL}}" },
    duplicateRisk: "medium",
    qaChecklist: ["Open chat widget → verify chat_click fires", "Check chat_provider set correctly"],
    implementationNotes: "Requires widget-specific callback integration — developer must implement dataLayer push on widget open",
    detectionKeywords: ["tidio", "intercom", "crisp", "zendesk", "tawk", "livechat", "drift", "freshchat"],
  },
  {
    eventKey: "social_click",
    displayName: "Social Media Click",
    description: "User clicks link to social media profile",
    websiteTypes: ["all"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "secondary",
    ga4EventName: "social_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["social_platform", "click_url"],
    optionalParameters: ["button_text", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on href containing facebook.com, instagram.com, tiktok.com, youtube.com, twitter.com, linkedin.com",
    dataLayerExample: { event: "social_click", social_platform: "facebook", click_url: "{{Click URL}}", button_text: "{{Click Text}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click social icon → verify social_click fires with correct social_platform"],
    implementationNotes: "GTM Click trigger with URL contains conditions per platform",
    detectionKeywords: ["facebook.com", "instagram.com", "tiktok.com", "youtube.com", "twitter.com", "linkedin.com"],
  },
  {
    eventKey: "map_click",
    displayName: "Map / Direction Click",
    description: "User clicks to open Google Maps or get directions",
    websiteTypes: ["local", "restaurant", "healthcare", "realestate"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "map_click",
    googleAdsCategory: "GET_DIRECTIONS",
    metaEventName: "FindLocation",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["click_url", "button_text"],
    optionalParameters: ["location_name", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on href containing maps.google, google.com/maps, goo.gl/maps, waze.com",
    dataLayerExample: { event: "map_click", event_id: "map_{{timestamp}}", click_url: "{{Click URL}}", button_text: "{{Click Text}}", location_name: "Main Branch" },
    duplicateRisk: "low",
    qaChecklist: ["Click map/direction button → verify map_click fires", "Check location_name populated"],
    implementationNotes: "KEY EVENT for local businesses",
    detectionKeywords: ["maps.google", "google.com/maps", "goo.gl/maps", "waze.com", "ขอเส้นทาง", "แผนที่", "นำทาง"],
  },
  {
    eventKey: "get_directions",
    displayName: "Get Directions",
    description: "User specifically clicks 'Get Directions' or 'Navigate'",
    websiteTypes: ["local", "restaurant"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "get_directions",
    googleAdsCategory: "GET_DIRECTIONS",
    metaEventName: "FindLocation",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["click_url"],
    optionalParameters: ["location_name", "branch_name"],
    triggerType: "click",
    triggerLogic: "Click on 'ขอเส้นทาง', 'Get Directions', 'นำทาง' button",
    dataLayerExample: { event: "get_directions", click_url: "{{Click URL}}", location_name: "Branch Name" },
    duplicateRisk: "low",
    qaChecklist: ["Click Get Directions → verify event fires"],
    implementationNotes: "Can merge with map_click or keep separate for clarity",
    detectionKeywords: ["get direction", "ขอเส้นทาง", "นำทาง", "direction"],
  },
  // ── Lead Events ───────────────────────────────────────────────
  {
    eventKey: "lead_form_view",
    displayName: "Lead Form View",
    description: "User views a lead/contact form on the page",
    websiteTypes: ["lead", "highticket", "healthcare", "realestate", "education", "b2b"],
    funnelStage: "consideration",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "lead_form_view",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id", "form_name"],
    optionalParameters: ["page_location"],
    triggerType: "page_view",
    triggerLogic: "Page containing form element is visible (page with form loaded)",
    dataLayerExample: { event: "lead_form_view", form_id: "contact_form", form_name: "Contact Form", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Load page with form → verify lead_form_view fires"],
    implementationNotes: "Optional — useful to measure form visibility vs. completion rate",
  },
  {
    eventKey: "form_start",
    displayName: "Form Start",
    description: "User first interacts with a form field — begins filling",
    websiteTypes: ["all"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "form_start",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: true,
    requiredParameters: ["form_id", "form_name"],
    optionalParameters: ["page_location"],
    triggerType: "click",
    triggerLogic: "First click/focus on any input inside the form — fire once per session per form",
    dataLayerExample: { event: "form_start", event_id: "fstart_{{timestamp}}", form_id: "contact_form", form_name: "Contact Form", page_location: "{{Page URL}}" },
    duplicateRisk: "high",
    qaChecklist: ["Click first form field → form_start fires", "Click second field → should NOT fire again", "Check form_id correct"],
    implementationNotes: "IMPORTANT: must fire only ONCE per form interaction. Use session-level dedup in GTM or developer code.",
  },
  {
    eventKey: "lead_start",
    displayName: "Lead Start",
    description: "User begins meaningful lead journey — entered name/phone/email",
    websiteTypes: ["lead", "highticket", "healthcare", "b2b"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "lead_start",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id"],
    optionalParameters: ["field_name", "lead_type"],
    triggerType: "custom_event",
    triggerLogic: "Developer pushes to dataLayer when user enters phone/email field with valid input",
    dataLayerExample: { event: "lead_start", form_id: "contact_form", field_name: "phone", lead_type: "contact" },
    duplicateRisk: "high",
    qaChecklist: ["Enter phone number → lead_start fires once", "Do not fire on blank fields"],
    implementationNotes: "Requires developer to implement — more accurate than form_start alone",
  },
  {
    eventKey: "lead_step_1",
    displayName: "Lead Step 1",
    description: "User completes step 1 of multi-step form",
    websiteTypes: ["lead", "highticket", "saas"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "lead_step_1",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id", "step_number"],
    optionalParameters: ["step_name"],
    triggerType: "custom_event",
    triggerLogic: "Developer pushes when multi-step form advances to step 2",
    dataLayerExample: { event: "lead_step_1", form_id: "multi_step_form", step_number: 1, step_name: "Basic Info" },
    duplicateRisk: "medium",
    qaChecklist: ["Complete step 1 → lead_step_1 fires", "Only fires on successful step advance"],
    implementationNotes: "Multi-step form only",
  },
  {
    eventKey: "lead_step_2",
    displayName: "Lead Step 2",
    description: "User completes step 2 of multi-step form",
    websiteTypes: ["lead", "highticket", "saas"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "lead_step_2",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id", "step_number"],
    optionalParameters: ["step_name"],
    triggerType: "custom_event",
    triggerLogic: "Developer pushes when multi-step form advances to step 3",
    dataLayerExample: { event: "lead_step_2", form_id: "multi_step_form", step_number: 2, step_name: "Requirements" },
    duplicateRisk: "medium",
    qaChecklist: ["Complete step 2 → lead_step_2 fires"],
    implementationNotes: "Multi-step form only",
  },
  {
    eventKey: "lead_step_3",
    displayName: "Lead Step 3",
    description: "User completes step 3 of multi-step form",
    websiteTypes: ["lead", "highticket", "saas"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "lead_step_3",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id", "step_number"],
    optionalParameters: ["step_name"],
    triggerType: "custom_event",
    triggerLogic: "Developer pushes when multi-step form advances past step 3",
    dataLayerExample: { event: "lead_step_3", form_id: "multi_step_form", step_number: 3, step_name: "Budget & Timing" },
    duplicateRisk: "medium",
    qaChecklist: ["Complete step 3 → lead_step_3 fires"],
    implementationNotes: "Multi-step form only",
  },
  {
    eventKey: "generate_lead",
    displayName: "Generate Lead",
    description: "CONFIRMED lead — form submitted successfully with server response",
    websiteTypes: ["lead", "highticket", "healthcare", "realestate", "education", "b2b"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "generate_lead",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: true,
    requiredParameters: ["form_id", "form_name", "lead_type", "value", "currency"],
    optionalParameters: ["transaction_id", "lead_source"],
    triggerType: "custom_event",
    triggerLogic: "MUST fire only after confirmed server success — redirect to thank-you page, success message shown, or AJAX callback success",
    dataLayerExample: { event: "generate_lead", event_id: "lead_{{timestamp}}", form_id: "contact_form", form_name: "Contact Form", lead_type: "contact_form", value: 300, currency: "THB", page_location: "{{Page URL}}" },
    duplicateRisk: "high",
    qaChecklist: [
      "Submit valid form → generate_lead fires",
      "Submit invalid form (validation error) → should NOT fire",
      "Refresh thank-you page → should NOT fire again",
      "Check value and currency populated",
      "Verify event appears in GA4 as conversion",
      "Verify Google Ads conversion fires"
    ],
    implementationNotes: "⚠️ CRITICAL: Must fire ONLY on confirmed success. If AJAX-based: detect success message or callback. If redirect-based: fire on thank-you page view. NEVER fire on button click alone.",
  },
  {
    eventKey: "request_quote",
    displayName: "Request Quote",
    description: "User submits a quotation request form",
    websiteTypes: ["b2b", "highticket", "realestate"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "request_quote",
    googleAdsCategory: "REQUEST_QUOTE",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["form_id", "value", "currency"],
    optionalParameters: ["service_name", "budget_range"],
    triggerType: "custom_event",
    triggerLogic: "Fire on confirmed quote form submission success",
    dataLayerExample: { event: "request_quote", event_id: "quote_{{timestamp}}", form_id: "quote_form", form_name: "Request Quote Form", lead_type: "quote", value: 500, currency: "THB" },
    duplicateRisk: "high",
    qaChecklist: ["Submit quote form → request_quote fires", "Check value/currency parameters"],
    implementationNotes: "KEY EVENT for B2B and high-ticket — configure as primary in Google Ads REQUEST_QUOTE",
    detectionKeywords: ["ขอใบเสนอราคา", "ขอราคา", "Request Quote", "Get Quote"],
  },
  {
    eventKey: "schedule",
    displayName: "Schedule / Appointment",
    description: "User books an appointment or schedules a meeting",
    websiteTypes: ["healthcare", "education", "booking", "saas", "b2b"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "schedule",
    googleAdsCategory: "BOOK_APPOINTMENT",
    metaEventName: "Schedule",
    tiktokEventName: "Schedule",
    isStandardEvent: false,
    requiredParameters: ["booking_type", "value", "currency"],
    optionalParameters: ["service_name", "selected_date", "selected_time"],
    triggerType: "custom_event",
    triggerLogic: "Fire on confirmed booking/appointment submission",
    dataLayerExample: { event: "schedule", event_id: "appt_{{timestamp}}", booking_type: "appointment", service_name: "Consultation", selected_date: "", selected_time: "", value: 500, currency: "THB" },
    duplicateRisk: "high",
    qaChecklist: ["Complete booking → schedule fires", "Verify booking_type correct", "Check Google Ads BOOK_APPOINTMENT fires"],
    implementationNotes: "KEY EVENT for healthcare, clinics, education",
    detectionKeywords: ["นัดหมาย", "จองคิว", "Book", "Appointment", "Schedule", "Calendar"],
  },
  {
    eventKey: "book_appointment",
    displayName: "Book Appointment",
    description: "Alias for schedule — explicit booking confirmation",
    websiteTypes: ["healthcare", "education", "booking"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "book_appointment",
    googleAdsCategory: "BOOK_APPOINTMENT",
    metaEventName: "Schedule",
    tiktokEventName: "Schedule",
    isStandardEvent: false,
    requiredParameters: ["service_name", "value", "currency"],
    optionalParameters: ["selected_date", "selected_time", "branch_name"],
    triggerType: "custom_event",
    triggerLogic: "Fire on confirmed appointment booking",
    dataLayerExample: { event: "book_appointment", event_id: "book_{{timestamp}}", service_name: "Service", value: 500, currency: "THB" },
    duplicateRisk: "high",
    qaChecklist: ["Complete appointment booking → book_appointment fires"],
    implementationNotes: "Use instead of schedule if the client wants explicit booking tracking",
    detectionKeywords: ["จอง", "จองคิว", "Book Now", "Reserve", "นัดหมาย"],
  },
  {
    eventKey: "thank_you_page_view",
    displayName: "Thank You Page",
    description: "User arrives at order/submission confirmation page",
    websiteTypes: ["all"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "thank_you_page_view",
    googleAdsCategory: "SUBMIT_LEAD_FORM",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["page_location"],
    optionalParameters: ["form_name", "transaction_id"],
    triggerType: "page_view",
    triggerLogic: "Page URL contains /thank-you/, /success/, /complete/, /confirm/, /order-received",
    dataLayerExample: { event: "thank_you_page_view", page_location: "{{Page URL}}", form_name: "Contact Form" },
    duplicateRisk: "high",
    qaChecklist: ["Submit form → land on thank-you page → event fires", "Refresh thank-you page → check if duplicate prevention works", "Verify URL-based trigger matches"],
    implementationNotes: "⚠️ Add dedup: use GTM session cookie to prevent refires on page refresh",
  },
  {
    eventKey: "qualify_lead",
    displayName: "Qualified Lead",
    description: "Lead passed qualification criteria — CRM event or human-marked",
    websiteTypes: ["highticket", "realestate", "b2b"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "qualify_lead",
    googleAdsCategory: "QUALIFIED_LEAD",
    metaEventName: "Lead",
    tiktokEventName: "SubmitForm",
    isStandardEvent: false,
    requiredParameters: ["lead_id", "value", "currency"],
    optionalParameters: ["qualification_score", "sales_stage"],
    triggerType: "custom_event",
    triggerLogic: "CRM webhook or Offline Conversion Import — not a browser event",
    dataLayerExample: { event: "qualify_lead", lead_id: "CRM-001", value: 5000, currency: "THB", qualification_score: "hot" },
    duplicateRisk: "low",
    qaChecklist: ["CRM sends qualified lead → verify import to Google Ads", "Check enhanced conversion matching works"],
    implementationNotes: "Requires Google Ads Offline Conversion Import or CRM-GTM integration",
  },
  {
    eventKey: "close_convert_lead",
    displayName: "Converted Lead / Closed Deal",
    description: "Lead converted to paying customer — highest value event",
    websiteTypes: ["highticket", "realestate", "b2b"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "close_convert_lead",
    googleAdsCategory: "CONVERTED_LEAD",
    metaEventName: "Purchase",
    tiktokEventName: "Purchase",
    isStandardEvent: false,
    requiredParameters: ["lead_id", "value", "currency", "transaction_id"],
    optionalParameters: ["sales_rep", "close_reason"],
    triggerType: "custom_event",
    triggerLogic: "CRM webhook or Offline Conversion Import — not a browser event",
    dataLayerExample: { event: "close_convert_lead", transaction_id: "DEAL-001", lead_id: "CRM-001", value: 50000, currency: "THB" },
    duplicateRisk: "low",
    qaChecklist: ["CRM closes deal → verify offline conversion imported", "Ensure transaction_id unique per deal"],
    implementationNotes: "Google Ads Offline Conversion Import — use same click ID from original ad click",
  },
  {
    eventKey: "lead_disqualified",
    displayName: "Lead Disqualified",
    description: "Lead did not meet criteria — for negative signal optimization",
    websiteTypes: ["highticket", "b2b"],
    funnelStage: "diagnostic",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "lead_disqualified",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["lead_id", "disqualify_reason"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "CRM event when lead is marked as disqualified",
    dataLayerExample: { event: "lead_disqualified", lead_id: "CRM-001", disqualify_reason: "wrong_budget" },
    duplicateRisk: "low",
    qaChecklist: ["Mark lead as disqualified in CRM → verify event imported"],
    implementationNotes: "Optional — used for audience suppression and negative signals",
  },
  // ── Registration / Subscription ────────────────────────────────
  {
    eventKey: "sign_up_click",
    displayName: "Sign Up Click",
    description: "User clicks sign up / register button",
    websiteTypes: ["saas"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "sign_up_click",
    googleAdsCategory: "SIGN_UP",
    metaEventName: "CompleteRegistration",
    tiktokEventName: "CompleteRegistration",
    isStandardEvent: false,
    requiredParameters: ["button_text", "click_url"],
    optionalParameters: ["plan_name"],
    triggerType: "click",
    triggerLogic: "Click on sign up or register CTA",
    dataLayerExample: { event: "sign_up_click", button_text: "Sign Up Free", click_url: "{{Click URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click Sign Up → verify event fires"],
    implementationNotes: "Secondary — confirm with sign_up after successful registration",
    detectionKeywords: ["Sign Up", "Register", "สมัคร", "ลงทะเบียน"],
  },
  {
    eventKey: "sign_up",
    displayName: "Sign Up Complete",
    description: "User successfully created an account",
    websiteTypes: ["saas"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "sign_up",
    googleAdsCategory: "SIGN_UP",
    metaEventName: "CompleteRegistration",
    tiktokEventName: "CompleteRegistration",
    isStandardEvent: true,
    requiredParameters: ["method"],
    optionalParameters: ["plan_name", "referral_source"],
    triggerType: "custom_event",
    triggerLogic: "Fire on confirmed account creation — developer pushes after API success",
    dataLayerExample: { event: "sign_up", event_id: "reg_{{timestamp}}", method: "email", plan_name: "free", page_location: "{{Page URL}}" },
    duplicateRisk: "high",
    qaChecklist: ["Complete registration → sign_up fires", "Check method parameter", "Verify GA4 marks as conversion"],
    implementationNotes: "KEY EVENT for SaaS — fire only after confirmed account creation",
  },
  {
    eventKey: "complete_registration",
    displayName: "Complete Registration",
    description: "User completes full registration (profile, verification, etc.)",
    websiteTypes: ["saas", "education"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "complete_registration",
    googleAdsCategory: "SIGN_UP",
    metaEventName: "CompleteRegistration",
    tiktokEventName: "CompleteRegistration",
    isStandardEvent: false,
    requiredParameters: ["registration_id"],
    optionalParameters: ["plan_name", "referral_source"],
    triggerType: "custom_event",
    triggerLogic: "Fire after user completes all onboarding/verification steps",
    dataLayerExample: { event: "complete_registration", event_id: "reg_{{timestamp}}", registration_id: "REG-001", plan_name: "starter" },
    duplicateRisk: "high",
    qaChecklist: ["Complete all registration steps → event fires once"],
    implementationNotes: "Use if registration is multi-step and completion matters more than initial signup",
  },
  {
    eventKey: "login",
    displayName: "Login",
    description: "User logs into existing account",
    websiteTypes: ["saas"],
    funnelStage: "retention",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "login",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["method"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "Fire after successful login",
    dataLayerExample: { event: "login", method: "email" },
    duplicateRisk: "low",
    qaChecklist: ["Log in → verify event fires with method"],
    implementationNotes: "Usually diagnostic only — not a conversion",
  },
  {
    eventKey: "subscribe",
    displayName: "Subscribe",
    description: "User subscribes to newsletter or paid plan",
    websiteTypes: ["saas", "content"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "subscribe",
    googleAdsCategory: "SUBSCRIBE",
    metaEventName: "Subscribe",
    tiktokEventName: "Subscribe",
    isStandardEvent: false,
    requiredParameters: ["subscription_type", "value", "currency"],
    optionalParameters: ["plan_name"],
    triggerType: "custom_event",
    triggerLogic: "Fire after confirmed subscription signup",
    dataLayerExample: { event: "subscribe", event_id: "sub_{{timestamp}}", subscription_type: "newsletter", value: 0, currency: "THB" },
    duplicateRisk: "high",
    qaChecklist: ["Subscribe → verify event fires with subscription_type"],
    implementationNotes: "KEY EVENT — ensure not fired on button click, only confirmed subscription",
    detectionKeywords: ["Subscribe", "สมัครรับข่าวสาร", "Newsletter"],
  },
  {
    eventKey: "start_trial",
    displayName: "Start Free Trial",
    description: "User activates a free trial",
    websiteTypes: ["saas"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "start_trial",
    googleAdsCategory: "SIGN_UP",
    metaEventName: "Subscribe",
    tiktokEventName: "CompleteRegistration",
    isStandardEvent: false,
    requiredParameters: ["plan_name", "trial_days"],
    optionalParameters: ["value", "currency"],
    triggerType: "custom_event",
    triggerLogic: "Fire after trial activation confirmed",
    dataLayerExample: { event: "start_trial", event_id: "trial_{{timestamp}}", plan_name: "pro_trial", trial_days: 14 },
    duplicateRisk: "high",
    qaChecklist: ["Start trial → event fires with correct plan_name and trial_days"],
    implementationNotes: "KEY EVENT for SaaS",
    detectionKeywords: ["Free Trial", "ทดลองฟรี", "Trial"],
  },
  {
    eventKey: "select_plan",
    displayName: "Select Plan",
    description: "User selects a pricing plan",
    websiteTypes: ["saas"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "select_plan",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["plan_name", "plan_price", "currency"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on plan selection button/card",
    dataLayerExample: { event: "select_plan", plan_name: "Pro", plan_price: 990, currency: "THB" },
    duplicateRisk: "low",
    qaChecklist: ["Select a plan → verify event fires with plan details"],
    implementationNotes: "Secondary — high intent signal before purchase/subscription",
  },
  {
    eventKey: "upgrade",
    displayName: "Upgrade Plan",
    description: "Existing user upgrades to higher plan",
    websiteTypes: ["saas"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "upgrade",
    googleAdsCategory: "PURCHASE",
    metaEventName: "Subscribe",
    tiktokEventName: "Subscribe",
    isStandardEvent: false,
    requiredParameters: ["from_plan", "to_plan", "value", "currency"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "Fire after confirmed plan upgrade",
    dataLayerExample: { event: "upgrade", event_id: "upg_{{timestamp}}", from_plan: "starter", to_plan: "pro", value: 990, currency: "THB" },
    duplicateRisk: "high",
    qaChecklist: ["Upgrade plan → verify event fires with from/to plan details"],
    implementationNotes: "KEY RETENTION event for SaaS",
  },
  // ── Ecommerce Events ──────────────────────────────────────────
  {
    eventKey: "view_item_list",
    displayName: "View Item List",
    description: "User views product category/listing page",
    websiteTypes: ["ecommerce"],
    funnelStage: "awareness",
    priority: "medium",
    conversionRole: "remarketing",
    ga4EventName: "view_item_list",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["item_list_id", "item_list_name", "items"],
    optionalParameters: [],
    triggerType: "page_view",
    triggerLogic: "Page is a product category/listing page",
    dataLayerExample: { event: "view_item_list", item_list_id: "category_slug", item_list_name: "Category Name", items: [{ item_id: "SKU001", item_name: "Product", price: 100, quantity: 1 }] },
    duplicateRisk: "low",
    qaChecklist: ["Visit category page → view_item_list fires with items array"],
    implementationNotes: "Developer must populate items array from page data",
  },
  {
    eventKey: "select_item",
    displayName: "Select Item",
    description: "User clicks on a product card from list",
    websiteTypes: ["ecommerce"],
    funnelStage: "consideration",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "select_item",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["items", "item_list_id"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on product card in list/category page",
    dataLayerExample: { event: "select_item", item_list_id: "category_slug", items: [{ item_id: "SKU001", item_name: "Product", price: 100, quantity: 1, index: 1 }] },
    duplicateRisk: "low",
    qaChecklist: ["Click product in list → select_item fires with correct item_id"],
    implementationNotes: "Developer must add click handler to product cards",
  },
  {
    eventKey: "view_item",
    displayName: "View Item (Product Page)",
    description: "User views individual product detail page",
    websiteTypes: ["ecommerce"],
    funnelStage: "consideration",
    priority: "high",
    conversionRole: "remarketing",
    ga4EventName: "view_item",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: [],
    triggerType: "page_view",
    triggerLogic: "Page is a single product detail page",
    dataLayerExample: { event: "view_item", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", item_category: "Category", price: 990, quantity: 1 }] },
    duplicateRisk: "low",
    qaChecklist: ["Visit product page → view_item fires", "Check items array has correct item_id, item_name, price"],
    implementationNotes: "Developer populates from product page data — KEY remarketing event",
  },
  {
    eventKey: "add_to_wishlist",
    displayName: "Add to Wishlist",
    description: "User adds product to wishlist/favorites",
    websiteTypes: ["ecommerce"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "secondary",
    ga4EventName: "add_to_wishlist",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "AddToWishlist",
    tiktokEventName: "AddToWishlist",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on wishlist/heart/favorite button on product",
    dataLayerExample: { event: "add_to_wishlist", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }] },
    duplicateRisk: "medium",
    qaChecklist: ["Click wishlist → add_to_wishlist fires with items"],
    implementationNotes: "Standard event — developer adds to wishlist button handler",
    detectionKeywords: ["wishlist", "favorite", "ชื่นชอบ", "บันทึก"],
  },
  {
    eventKey: "add_to_cart",
    displayName: "Add to Cart",
    description: "User adds item to shopping cart",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "secondary",
    ga4EventName: "add_to_cart",
    googleAdsCategory: "ADD_TO_CART",
    metaEventName: "AddToCart",
    tiktokEventName: "AddToCart",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click Add to Cart button AND cart API confirms item added (not just button click)",
    dataLayerExample: { event: "add_to_cart", event_id: "atc_{{timestamp}}", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", item_category: "Category", price: 990, quantity: 1 }] },
    duplicateRisk: "medium",
    qaChecklist: ["Click Add to Cart → event fires", "Verify items array correct", "Do NOT fire if add to cart fails", "Check event_id for dedup"],
    implementationNotes: "⚠️ Must fire ONLY on successful add — wait for API confirmation",
    detectionKeywords: ["add to cart", "เพิ่มลงตะกร้า", "ใส่ตะกร้า", "Buy Now"],
  },
  {
    eventKey: "remove_from_cart",
    displayName: "Remove from Cart",
    description: "User removes item from cart",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "remove_from_cart",
    googleAdsCategory: "ADD_TO_CART",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click remove button in cart page",
    dataLayerExample: { event: "remove_from_cart", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }] },
    duplicateRisk: "low",
    qaChecklist: ["Remove item from cart → event fires"],
    implementationNotes: "Diagnostic — useful to analyze cart abandonment",
  },
  {
    eventKey: "view_cart",
    displayName: "View Cart",
    description: "User views cart page",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "view_cart",
    googleAdsCategory: "ADD_TO_CART",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: [],
    triggerType: "page_view",
    triggerLogic: "Cart page URL (/cart/, /basket/, /ตะกร้า/)",
    dataLayerExample: { event: "view_cart", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }] },
    duplicateRisk: "low",
    qaChecklist: ["Visit cart page → view_cart fires with all items"],
    implementationNotes: "Page view trigger on cart URL — developer populates items from cart state",
  },
  {
    eventKey: "begin_checkout",
    displayName: "Begin Checkout",
    description: "User starts checkout process",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "secondary",
    ga4EventName: "begin_checkout",
    googleAdsCategory: "BEGIN_CHECKOUT",
    metaEventName: "InitiateCheckout",
    tiktokEventName: "InitiateCheckout",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items"],
    optionalParameters: ["coupon"],
    triggerType: "page_view",
    triggerLogic: "Checkout page URL (/checkout/, /ชำระเงิน/) OR click 'Proceed to Checkout' button",
    dataLayerExample: { event: "begin_checkout", event_id: "co_{{timestamp}}", currency: "THB", value: 990, items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }], coupon: "" },
    duplicateRisk: "medium",
    qaChecklist: ["Click Proceed to Checkout → begin_checkout fires", "Check items array matches cart content", "Verify NOT firing on cart page view"],
    implementationNotes: "⚠️ Should fire when checkout STARTS — not on cart page view",
    detectionKeywords: ["checkout", "ชำระเงิน", "สั่งซื้อ", "Order Now"],
  },
  {
    eventKey: "add_shipping_info",
    displayName: "Add Shipping Info",
    description: "User enters and confirms shipping address",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "add_shipping_info",
    googleAdsCategory: "BEGIN_CHECKOUT",
    metaEventName: "AddPaymentInfo",
    tiktokEventName: "AddPaymentInfo",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items", "shipping_tier"],
    optionalParameters: ["coupon"],
    triggerType: "custom_event",
    triggerLogic: "Fire when user submits shipping step and advances to payment",
    dataLayerExample: { event: "add_shipping_info", currency: "THB", value: 990, shipping_tier: "standard", items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }] },
    duplicateRisk: "medium",
    qaChecklist: ["Submit shipping form → add_shipping_info fires"],
    implementationNotes: "Multi-step checkout — developer pushes after shipping step completion",
  },
  {
    eventKey: "add_payment_info",
    displayName: "Add Payment Info",
    description: "User enters payment information",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "add_payment_info",
    googleAdsCategory: "BEGIN_CHECKOUT",
    metaEventName: "AddPaymentInfo",
    tiktokEventName: "AddPaymentInfo",
    isStandardEvent: true,
    requiredParameters: ["currency", "value", "items", "payment_type"],
    optionalParameters: ["coupon"],
    triggerType: "custom_event",
    triggerLogic: "Fire when user selects payment method and advances",
    dataLayerExample: { event: "add_payment_info", currency: "THB", value: 990, payment_type: "credit_card", items: [{ item_id: "SKU001", item_name: "Product", price: 990, quantity: 1 }] },
    duplicateRisk: "medium",
    qaChecklist: ["Select payment method and continue → add_payment_info fires"],
    implementationNotes: "Multi-step checkout — developer pushes after payment info step",
  },
  {
    eventKey: "apply_coupon",
    displayName: "Apply Coupon",
    description: "User applies a discount coupon code",
    websiteTypes: ["ecommerce"],
    funnelStage: "intent",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "apply_coupon",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["coupon_code", "discount_value"],
    optionalParameters: ["currency"],
    triggerType: "click",
    triggerLogic: "Click Apply Coupon button with successful coupon application",
    dataLayerExample: { event: "apply_coupon", coupon_code: "SAVE20", discount_value: 200, currency: "THB" },
    duplicateRisk: "low",
    qaChecklist: ["Apply valid coupon → event fires with coupon_code"],
    implementationNotes: "Diagnostic — useful to track coupon usage and abandonment",
    detectionKeywords: ["coupon", "ส่วนลด", "โปรโมชัน", "promo code"],
  },
  {
    eventKey: "purchase",
    displayName: "Purchase",
    description: "CONFIRMED order completed — highest priority conversion",
    websiteTypes: ["ecommerce"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "purchase",
    googleAdsCategory: "PURCHASE",
    metaEventName: "Purchase",
    tiktokEventName: "Purchase",
    isStandardEvent: true,
    requiredParameters: ["transaction_id", "currency", "value", "items"],
    optionalParameters: ["tax", "shipping", "coupon", "affiliation"],
    triggerType: "custom_event",
    triggerLogic: "Fire ONLY on order confirmation page with unique transaction_id — server-confirmed order",
    dataLayerExample: {
      event: "purchase", event_id: "order_12345",
      transaction_id: "12345", currency: "THB", value: 1990, tax: 0, shipping: 50,
      items: [{ item_id: "SKU001", item_name: "Product Name", item_category: "Category", item_brand: "Brand", price: 1990, quantity: 1 }]
    },
    duplicateRisk: "high",
    qaChecklist: [
      "Complete purchase → purchase fires ONCE",
      "Refresh confirmation page → purchase should NOT fire again",
      "Check transaction_id is unique",
      "Verify items array complete with price and quantity",
      "Check value matches actual order total",
      "Verify currency = THB",
      "Check Google Ads PURCHASE conversion fires",
      "Check Meta Purchase event fires with same value"
    ],
    implementationNotes: "⚠️ MOST CRITICAL EVENT — NEVER fire on button click. Must be server-confirmed. Use session cookie or server-set variable to prevent refresh duplicates. Use transaction_id for cross-platform dedup.",
    detectionKeywords: ["thank you", "order confirmed", "order received", "ขอบคุณ", "ยืนยันคำสั่งซื้อ"],
  },
  {
    eventKey: "refund",
    displayName: "Refund",
    description: "Order refunded — for revenue reconciliation",
    websiteTypes: ["ecommerce"],
    funnelStage: "diagnostic",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "refund",
    googleAdsCategory: "PURCHASE",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: true,
    requiredParameters: ["transaction_id", "currency", "value"],
    optionalParameters: ["items"],
    triggerType: "custom_event",
    triggerLogic: "Backend sends refund event to GA4 via Measurement Protocol or GTM server",
    dataLayerExample: { event: "refund", transaction_id: "12345", currency: "THB", value: 1990 },
    duplicateRisk: "low",
    qaChecklist: ["Trigger refund → verify event in GA4 with negative revenue impact"],
    implementationNotes: "Backend/Measurement Protocol event — rarely via browser GTM",
  },
  // ── Local / Restaurant Events ─────────────────────────────────
  {
    eventKey: "view_location",
    displayName: "View Location",
    description: "User views a branch/location page",
    websiteTypes: ["local", "restaurant"],
    funnelStage: "consideration",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "view_location",
    googleAdsCategory: "GET_DIRECTIONS",
    metaEventName: "FindLocation",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["location_name", "page_location"],
    optionalParameters: ["branch_id"],
    triggerType: "page_view",
    triggerLogic: "Page URL contains /location/, /branch/, /สาขา/",
    dataLayerExample: { event: "view_location", location_name: "Branch Name", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Visit location page → view_location fires with location_name"],
    implementationNotes: "URL-based trigger — useful for multi-branch businesses",
  },
  {
    eventKey: "branch_select",
    displayName: "Branch Select",
    description: "User selects a specific branch from list",
    websiteTypes: ["local", "restaurant"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "branch_select",
    googleAdsCategory: "GET_DIRECTIONS",
    metaEventName: "FindLocation",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["branch_name"],
    optionalParameters: ["branch_id", "page_location"],
    triggerType: "click",
    triggerLogic: "Click on branch card or branch selector dropdown",
    dataLayerExample: { event: "branch_select", branch_name: "สาขาสยาม", branch_id: "branch_001" },
    duplicateRisk: "low",
    qaChecklist: ["Select branch → branch_select fires with branch_name"],
    implementationNotes: "For multi-branch businesses with branch selector UI",
  },
  {
    eventKey: "menu_view",
    displayName: "Menu View",
    description: "User views restaurant/product menu",
    websiteTypes: ["restaurant"],
    funnelStage: "consideration",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "menu_view",
    googleAdsCategory: "PAGE_VIEW",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["menu_type", "page_location"],
    optionalParameters: [],
    triggerType: "page_view",
    triggerLogic: "Page URL contains /menu/ or page has menu-specific content",
    dataLayerExample: { event: "menu_view", menu_type: "food_menu", page_location: "{{Page URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["View menu page → menu_view fires"],
    implementationNotes: "URL-based trigger",
    detectionKeywords: ["menu", "เมนู", "รายการอาหาร"],
  },
  {
    eventKey: "order_click",
    displayName: "Order Click",
    description: "User clicks online order button or delivery app link",
    websiteTypes: ["restaurant"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "order_click",
    googleAdsCategory: "PURCHASE",
    metaEventName: "InitiateCheckout",
    tiktokEventName: "InitiateCheckout",
    isStandardEvent: false,
    requiredParameters: ["order_method", "click_url"],
    optionalParameters: ["button_text"],
    triggerType: "click",
    triggerLogic: "Click order/delivery app button (GrabFood, LINE MAN, Foodpanda, etc.)",
    dataLayerExample: { event: "order_click", order_method: "grabfood", click_url: "{{Click URL}}", button_text: "Order Now" },
    duplicateRisk: "low",
    qaChecklist: ["Click order button → order_click fires with order_method"],
    implementationNotes: "KEY for restaurants — mark as primary if no in-house checkout",
    detectionKeywords: ["order", "สั่งอาหาร", "delivery", "Grabfood", "LINE MAN", "Foodpanda"],
  },
  {
    eventKey: "reserve_start",
    displayName: "Reserve Start",
    description: "User begins table reservation",
    websiteTypes: ["restaurant"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "reserve_start",
    googleAdsCategory: "BOOK_APPOINTMENT",
    metaEventName: "Schedule",
    tiktokEventName: "Schedule",
    isStandardEvent: false,
    requiredParameters: ["form_id"],
    optionalParameters: ["party_size"],
    triggerType: "click",
    triggerLogic: "Click on 'Reserve Table' or 'จองโต๊ะ' button",
    dataLayerExample: { event: "reserve_start", form_id: "reservation_form", party_size: 2 },
    duplicateRisk: "low",
    qaChecklist: ["Click Reserve Table → reserve_start fires"],
    implementationNotes: "Secondary — confirm with reserve_submit after form submission",
    detectionKeywords: ["จองโต๊ะ", "Reserve", "Reservation", "จอง"],
  },
  {
    eventKey: "reserve_submit",
    displayName: "Reserve Submit",
    description: "User successfully submits table reservation",
    websiteTypes: ["restaurant"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "reserve_submit",
    googleAdsCategory: "BOOK_APPOINTMENT",
    metaEventName: "Schedule",
    tiktokEventName: "Schedule",
    isStandardEvent: false,
    requiredParameters: ["form_id", "party_size", "selected_date"],
    optionalParameters: ["selected_time", "value", "currency"],
    triggerType: "custom_event",
    triggerLogic: "Fire after confirmed table reservation submission",
    dataLayerExample: { event: "reserve_submit", event_id: "res_{{timestamp}}", form_id: "reservation_form", party_size: 2, selected_date: "2026-07-01" },
    duplicateRisk: "high",
    qaChecklist: ["Submit reservation → reserve_submit fires once", "Check selected_date and party_size correct"],
    implementationNotes: "KEY EVENT for restaurants — fire only on confirmed reservation",
  },
  {
    eventKey: "delivery_app_click",
    displayName: "Delivery App Click",
    description: "User clicks to order via food delivery app",
    websiteTypes: ["restaurant"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "delivery_app_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "Contact",
    tiktokEventName: "Contact",
    isStandardEvent: false,
    requiredParameters: ["app_name", "click_url"],
    optionalParameters: ["button_text"],
    triggerType: "click",
    triggerLogic: "Click link to GrabFood, LINE MAN, Foodpanda, Robinhood, ShopeeFood",
    dataLayerExample: { event: "delivery_app_click", app_name: "grabfood", click_url: "{{Click URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click delivery app link → delivery_app_click fires with app_name"],
    implementationNotes: "Track per app — useful to measure which delivery app performs best",
    detectionKeywords: ["grabfood", "lineman", "foodpanda", "robinhood", "shopeefood"],
  },
  // ── Content / Affiliate Events ────────────────────────────────
  {
    eventKey: "affiliate_click",
    displayName: "Affiliate Link Click",
    description: "User clicks affiliate/partner product link",
    websiteTypes: ["affiliate", "content"],
    funnelStage: "intent",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "affiliate_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["affiliate_url", "merchant_name"],
    optionalParameters: ["product_name", "commission_estimate"],
    triggerType: "click",
    triggerLogic: "Click on affiliate link URL containing tracking parameters or known affiliate domains",
    dataLayerExample: { event: "affiliate_click", affiliate_url: "{{Click URL}}", merchant_name: "Lazada", product_name: "Product Name" },
    duplicateRisk: "low",
    qaChecklist: ["Click affiliate link → event fires with merchant_name"],
    implementationNotes: "KEY EVENT for affiliate sites — primary conversion",
    detectionKeywords: ["lazada", "shopee", "amazon", "partner", "affiliate"],
  },
  {
    eventKey: "toc_click",
    displayName: "Table of Contents Click",
    description: "User clicks in-page navigation / table of contents",
    websiteTypes: ["content"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "toc_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["section_name", "click_url"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on anchor link within page (#section)",
    dataLayerExample: { event: "toc_click", section_name: "Section Title", click_url: "#section-id" },
    duplicateRisk: "low",
    qaChecklist: ["Click TOC link → event fires with section_name"],
    implementationNotes: "Useful for long-form content engagement analysis",
  },
  {
    eventKey: "related_content_click",
    displayName: "Related Content Click",
    description: "User clicks recommended/related article",
    websiteTypes: ["content"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "related_content_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["content_title", "click_url"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on related articles section links",
    dataLayerExample: { event: "related_content_click", content_title: "Article Title", click_url: "{{Click URL}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click related article → event fires"],
    implementationNotes: "CSS selector trigger on related content section",
  },
  {
    eventKey: "newsletter_sign_up",
    displayName: "Newsletter Sign Up",
    description: "User subscribes to newsletter",
    websiteTypes: ["content", "saas"],
    funnelStage: "conversion",
    priority: "high",
    conversionRole: "primary",
    ga4EventName: "newsletter_sign_up",
    googleAdsCategory: "SIGN_UP",
    metaEventName: "Subscribe",
    tiktokEventName: "Subscribe",
    isStandardEvent: false,
    requiredParameters: ["form_id", "email"],
    optionalParameters: [],
    triggerType: "custom_event",
    triggerLogic: "Fire after confirmed newsletter subscription",
    dataLayerExample: { event: "newsletter_sign_up", event_id: "nl_{{timestamp}}", form_id: "newsletter_form" },
    duplicateRisk: "high",
    qaChecklist: ["Subscribe newsletter → fires once after confirmed", "Do NOT fire on submit click alone"],
    implementationNotes: "Must be confirmed subscription — check email validation and success state",
    detectionKeywords: ["newsletter", "subscribe", "สมัครรับข่าวสาร"],
  },
  // ── Utility / Interaction Events ──────────────────────────────
  {
    eventKey: "filter_use",
    displayName: "Filter Use",
    description: "User applies product/content filter",
    websiteTypes: ["ecommerce", "realestate"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "filter_use",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["filter_type", "filter_value"],
    optionalParameters: ["page_location"],
    triggerType: "click",
    triggerLogic: "Click on filter option (price range, category, location, etc.)",
    dataLayerExample: { event: "filter_use", filter_type: "price_range", filter_value: "1000-5000" },
    duplicateRisk: "low",
    qaChecklist: ["Apply filter → filter_use fires with filter_type and filter_value"],
    implementationNotes: "Diagnostic — reveals user intent and preferences",
  },
  {
    eventKey: "sort_use",
    displayName: "Sort Use",
    description: "User changes product/content sort order",
    websiteTypes: ["ecommerce"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "sort_use",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["sort_by"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on sort dropdown option",
    dataLayerExample: { event: "sort_use", sort_by: "price_asc" },
    duplicateRisk: "low",
    qaChecklist: ["Change sort → sort_use fires with sort_by"],
    implementationNotes: "Diagnostic — understand browse behavior",
  },
  {
    eventKey: "calculator_use",
    displayName: "Calculator Use",
    description: "User interacts with loan/price/ROI calculator",
    websiteTypes: ["realestate", "highticket", "b2b"],
    funnelStage: "intent",
    priority: "medium",
    conversionRole: "secondary",
    ga4EventName: "calculator_use",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["calculator_type", "result_value"],
    optionalParameters: ["currency"],
    triggerType: "custom_event",
    triggerLogic: "User submits calculator form or changes calculator inputs",
    dataLayerExample: { event: "calculator_use", calculator_type: "loan_calculator", result_value: 15000, currency: "THB" },
    duplicateRisk: "low",
    qaChecklist: ["Use calculator → calculator_use fires with result_value"],
    implementationNotes: "High intent for real estate and financial products",
  },
  {
    eventKey: "compare_item",
    displayName: "Compare Items",
    description: "User adds items to comparison",
    websiteTypes: ["ecommerce"],
    funnelStage: "consideration",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "compare_item",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["items"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click Compare button on product",
    dataLayerExample: { event: "compare_item", items: [{ item_id: "SKU001" }, { item_id: "SKU002" }] },
    duplicateRisk: "low",
    qaChecklist: ["Add to compare → compare_item fires"],
    implementationNotes: "Optional diagnostic event",
  },
  {
    eventKey: "copy_coupon",
    displayName: "Copy Coupon",
    description: "User copies a coupon code",
    websiteTypes: ["ecommerce", "content"],
    funnelStage: "intent",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "copy_coupon",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["coupon_code"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click copy coupon button",
    dataLayerExample: { event: "copy_coupon", coupon_code: "SAVE20" },
    duplicateRisk: "low",
    qaChecklist: ["Click copy coupon → event fires with coupon_code"],
    implementationNotes: "Optional — useful for affiliate coupon tracking",
  },
  {
    eventKey: "share_click",
    displayName: "Share Click",
    description: "User clicks share button",
    websiteTypes: ["content", "ecommerce"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "share_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["share_method", "content_type"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on share button (Facebook, LINE, Twitter, etc.)",
    dataLayerExample: { event: "share_click", share_method: "facebook", content_type: "article" },
    duplicateRisk: "low",
    qaChecklist: ["Click share → event fires with share_method"],
    implementationNotes: "Optional — for content virality tracking",
  },
  {
    eventKey: "print_click",
    displayName: "Print Click",
    description: "User clicks print button",
    websiteTypes: ["content"],
    funnelStage: "engagement",
    priority: "low",
    conversionRole: "diagnostic",
    ga4EventName: "print_click",
    googleAdsCategory: "ENGAGEMENT",
    metaEventName: "ViewContent",
    tiktokEventName: "ViewContent",
    isStandardEvent: false,
    requiredParameters: ["page_title"],
    optionalParameters: [],
    triggerType: "click",
    triggerLogic: "Click on print button or Ctrl+P",
    dataLayerExample: { event: "print_click", page_title: "{{Page Title}}" },
    duplicateRisk: "low",
    qaChecklist: ["Click print → event fires"],
    implementationNotes: "Optional — mostly for brochure/menu sites",
  },
];

// ── Helper functions ─────────────────────────────────────────────

export function getEventByKey(key: string): EventDefinition | undefined {
  return EVENT_LIBRARY.find(e => e.eventKey === key);
}

export function getEventsForWebsiteTypes(types: WebsiteType[]): EventDefinition[] {
  return EVENT_LIBRARY.filter(e =>
    e.websiteTypes.includes("all") || types.some(t => e.websiteTypes.includes(t))
  );
}

export function getPrimaryConversionEvents(types: WebsiteType[]): EventDefinition[] {
  return getEventsForWebsiteTypes(types).filter(e => e.conversionRole === "primary");
}

export const WEBSITE_TYPE_LABELS: Record<WebsiteType, string> = {
  all:        "ทุกประเภท",
  lead:       "Lead Generation",
  ecommerce:  "E-commerce",
  booking:    "Booking / Appointment",
  local:      "Local Business",
  content:    "Content / Blog",
  saas:       "SaaS / Subscription",
  highticket: "High-ticket / B2B",
  restaurant: "Restaurant / Food",
  realestate: "Real Estate",
  education:  "Education / Course",
  healthcare: "Healthcare / Clinic",
  b2b:        "B2B Service",
  affiliate:  "Affiliate",
};

export const DETECTION_KEYWORDS = {
  line:     ["line.me", "lin.ee", "page.line.me", "LINE", "ไลน์", "แอดไลน์", "ทักไลน์", "เพิ่มเพื่อน"],
  phone:    ["tel:", "โทร", "โทรเลย", "Call", "Call Now", "เบอร์โทร", "ติดต่อเบอร์", "โทรปรึกษา"],
  email:    ["mailto:", "email", "Email", "อีเมล", "ส่งอีเมล"],
  map:      ["maps.google", "google.com/maps", "goo.gl/maps", "waze.com", "ขอเส้นทาง", "แผนที่", "นำทาง"],
  form:     ["submit", "ส่งข้อมูล", "ส่งฟอร์ม", "สมัคร", "ขอใบเสนอราคา", "นัดหมาย", "จองคิว", "Book", "Register", "Sign Up", "Send"],
  ecommerce:["add to cart", "เพิ่มลงตะกร้า", "buy now", "ซื้อเลย", "checkout", "ชำระเงิน", "cart", "ตะกร้า"],
  booking:  ["booking", "จอง", "จองคิว", "appointment", "schedule", "นัดหมาย", "calendar", "reserve"],
  social:   ["facebook.com", "instagram.com", "tiktok.com", "youtube.com", "twitter.com", "linkedin.com"],
  whatsapp: ["wa.me", "whatsapp"],
  messenger:["m.me", "messenger"],
};

export const TRACKING_HEALTH_WEIGHTS = {
  hasGtm:               10,
  hasGa4:               10,
  hasGoogleAds:         10,
  hasMeta:              10,
  hasTiktok:            10,
  hasConsentMode:       10,
  hasPrimaryConversions: 15,
  hasFunnelEvents:      15,
  hasDeduplication:      5,
  hasQaPlan:             5,
} as const;
